apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpserver
spec:
  gateways:
    - httpserver
  hosts:
    - '*'
  http:
    - match:
        - port: 80
      route:
        - destination:
        #svc.namespace..svc.cluster.local
            host: httpserver.httpserver.svc.cluster.local
            port:
              number: 80

